import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';
import styled from 'styled-components';
import Checkbox from '@mui/material/Checkbox';


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button variant='text'>Hello World</Button>
      <Checkbox variant='danger' />
    </div>
  )
}
